repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
      - id: mutmut
        name: mutation-testing
        entry: mutmut run
        language: system
        types: [python]
