repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff format
        language: system
        types: [python]
      - id: pytest
        name: unit-testing
        entry: pytest
        language: system
        types: [python]
